# Generated by Django 4.2.3 on 2023-07-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empresa', models.CharField(max_length=10, unique=True)),
                ('nombre_empresa', models.CharField(max_length=20)),
                ('direccion_empresa', models.CharField(max_length=50)),
                ('ciudad_empresa', models.CharField(max_length=20)),
                ('email_empresa', models.EmailField(max_length=40)),
                ('fono_empresa', models.IntegerField(max_length=10)),
                ('rubro_empresa', models.CharField(max_length=30)),
            ],
        ),
    ]
