# Generated by Django 4.2.3 on 2023-07-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_2', '0002_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='fono_empresa',
            field=models.CharField(max_length=12),
        ),
    ]
