# Generated by Django 4.2.3 on 2023-07-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_2', '0003_alter_proveedores_fono_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='ciudad_empresa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='direccion_empresa',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre_empresa',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='rubro_empresa',
            field=models.CharField(max_length=50),
        ),
    ]
